language: c
script: ./buildall.sh
before_install:
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap
  - ./travis-tool.sh install_github rstudio/rmarkdown
install:
  - ./travis-tool.sh install_deps
notifications:
  email:
    on_success: change
    on_failure: change
