language: c
script: ./buildall.sh
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq haskell-platform
  - cabal update
  - sudo cabal install --global pandoc
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap
  - ./travis-tool.sh install_github rstudio/rmarkdown
notifications:
  email:
    on_success: change
    on_failure: change
